on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    container: ubuntu:latest
    services:
      dynamodb-local:
        image: amazon/dynamodb-local:3.0.0
        ports:
          - 8000:8000/tcp
    strategy:
      matrix:
        php-versions: ['8.1', '8.2', '8.3']
    env: 
      AWS_ACCESS_KEY_ID: 'none'
      AWS_SECRET_ACCESS_KEY: 'none'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install git
        run: |
          apt-get update && apt-get install -y --no-install-recommends git

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer
          coverage: xdebug

      - name: Validate composer.json
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run phpunit
        run: composer run-script phpunit

      - name: Run phpstan
        run: composer run-script phpstan
